### ISSUE TITLE
執行問題

### ISSUE THREAD

**Issue by ivanjj55** [ChienKaiMa/AlphaMove#1]
無法make linux18，而且在MakeFile最後的cd ref無法執行QAQ

**Comment by ivanjj55** [comment]
請問ref資料夾的用途是甚麼或在哪裡，感謝回復~
![image](https://user-images.githubusercontent.com/73174835/119029066-c4299280-b9da-11eb-9112-0aa9768ea98c.png)

**Comment by ChienKaiMa** [comment]
假如你是用 Ubuntu 18 的話，可以直接打 `make`，不需要 `make linux18`。這個 `ref` 資料夾跟這個 project 無關，所以你可以把 Makefile 第 61 行註解掉再試試看。
